import React from 'react';
import type { NextPage } from 'next';
import "isomorphic-fetch";
import Head from 'next/head';
import Link from 'next/link';

import { Navbar } from '../src/components/Navbar/Navbar';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title> DropLinkFy | Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
        <h1 className="text-red-700 abcdaamazonia">Hello, worldsadisadjia!</h1>
    </>
  )
}

export default Home
