import React from 'react';
import type { NextPage } from 'next';
import "isomorphic-fetch";
import Head from 'next/head';
import Link from 'next/link';

import { Navbar } from '../src/components/Navbar/index';
import { HomeSection } from '../src/components/HomeSection/index';
import { VideoSection } from '../src/components/VideoSection/index';
import { Benefits } from '../src/components/Benefits/index';
import { PricingCard } from '../src/components/PricingCard/index';
import { ServicesSection } from '../src/components/ServicesSection/index';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title> DroplinkFy | Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HomeSection />
      <VideoSection />
      <Benefits />
      <PricingCard />
      <ServicesSection />
    </>
  )
}

export default Home
